# Generated by Django 2.1.5 on 2019-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190226_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Mantenimiento'), ('o', 'En prestamo'), ('a', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Book availability', max_length=1),
        ),
    ]
